export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN';
export const ADD_MAIN: 'ADD_MAIN' = 'ADD_MAIN';
export const DELETE_MAIN_ELEMENT: 'DELETE_MAIN_ELEMENT' = 'DELETE_MAIN_ELEMENT';
export const REORDER_MAIN_ELEMENTS: 'REORDER_MAIN_ELEMENTS' = 'REORDER_MAIN_ELEMENTS';
