//типизация всех типов экшенов

//авторизация

export const ADD_USER_INFO: 'ADD_USER_INFO' = 'ADD_USER_INFO';
export const EDIT_USER: 'EDIT_USER' = 'EDIT_USER';
export const DEL_USER_INFO: 'DEL_USER_INFO' = 'DEL_USER_INFO';
export const GET_FORGOT_PASS: 'GET_FORGOT_PASS' = 'GET_FORGOT_PASS';
export const GET_FORGOT_PASS_SUCCESS: 'GET_FORGOT_PASS_SUCCESS' = 'GET_FORGOT_PASS_SUCCESS';
export const GET_FORGOT_PASS_FAIL: 'GET_FORGOT_PASS_FAIL' = 'GET_FORGOT_PASS_FAIL';
export const SEND_LOGOUT: 'SEND_LOGOUT' = 'SEND_LOGOUT';
export const SEND_LOGOUT_FAIL: 'SEND_LOGOUT_FAIL' = 'SEND_LOGOUT_FAIL';
export const GET_USER_INFO: 'GET_USER_INFO' = 'GET_USER_INFO';
export const NEED_REFRESH_TOKEN: 'NEED_REFRESH_TOKEN' = 'NEED_REFRESH_TOKEN';
export const GET_TOKEN: 'GET_TOKEN' = 'GET_TOKEN';
export const TOKEN_REFRESH_SUCCESS: 'TOKEN_REFRESH_SUCCESS' = 'TOKEN_REFRESH_SUCCESS';
export const PASS_UPDATE_SUCCESS: 'PASS_UPDATE_SUCCESS' = 'PASS_UPDATE_SUCCESS';

//бургер - конструктор
export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN';
export const ADD_MAIN: 'ADD_MAIN' = 'ADD_MAIN';
export const DELETE_MAIN_ELEMENT: 'DELETE_MAIN_ELEMENT' = 'DELETE_MAIN_ELEMENT';
export const REORDER_MAIN_ELEMENTS: 'REORDER_MAIN_ELEMENTS' = 'REORDER_MAIN_ELEMENTS';


//бургер - ингридиент
export const GET_ITEMS_SUCCESS: 'GET_ITEMS_SUCCESS' = 'GET_ITEMS_SUCCESS';
export const ADD_COUNT_INGRIDIENT: 'ADD_COUNT_INGRIDIENT' = 'ADD_COUNT_INGRIDIENT';
export const DELETE_COUNT_BUN: 'DELETE_COUNT_BUN' = 'DELETE_COUNT_BUN';


//модальное окно детали ингидиента
export const OPEN_ITEM: 'OPEN_ITEM' = 'OPEN_ITEM';
export const CLOSE_ITEM: 'CLOSE_ITEM' = 'CLOSE_ITEM';


// оформление заказа
export const ADD_LIST_ORDER: 'ADD_LIST_ORDER' = 'ADD_LIST_ORDER';
export const ADD_NUMBER_ORDER: 'ADD_NUMBER_ORDER' = 'ADD_NUMBER_ORDER';
export const ADD_LIST_ORDER_FAIL: 'ADD_LIST_ORDER_FAIL' = 'ADD_LIST_ORDER_FAIL';


//модальное окно для истории заказов
export const OPEN_ITEM_FEED: 'OPEN_ITEM_FEED' = 'OPEN_ITEM_FEED';
export const CLOSE_ITEM_FEED: 'CLOSE_ITEM_FEED' = 'CLOSE_ITEM_FEED';

